// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetCredsClient is the client API for GetCreds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetCredsClient interface {
	GenerateToken(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getCredsClient struct {
	cc grpc.ClientConnInterface
}

func NewGetCredsClient(cc grpc.ClientConnInterface) GetCredsClient {
	return &getCredsClient{cc}
}

func (c *getCredsClient) GenerateToken(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/creds.GetCreds/GenerateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCredsServer is the server API for GetCreds service.
// All implementations should embed UnimplementedGetCredsServer
// for forward compatibility
type GetCredsServer interface {
	GenerateToken(context.Context, *Request) (*Response, error)
}

// UnimplementedGetCredsServer should be embedded to have forward compatible implementations.
type UnimplementedGetCredsServer struct {
}

func (UnimplementedGetCredsServer) GenerateToken(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}

// UnsafeGetCredsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetCredsServer will
// result in compilation errors.
type UnsafeGetCredsServer interface {
	mustEmbedUnimplementedGetCredsServer()
}

func RegisterGetCredsServer(s grpc.ServiceRegistrar, srv GetCredsServer) {
	s.RegisterService(&GetCreds_ServiceDesc, srv)
}

func _GetCreds_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetCredsServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creds.GetCreds/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetCredsServer).GenerateToken(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GetCreds_ServiceDesc is the grpc.ServiceDesc for GetCreds service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetCreds_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "creds.GetCreds",
	HandlerType: (*GetCredsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateToken",
			Handler:    _GetCreds_GenerateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/creds.proto",
}
